### PR TITLE
PSR and readme update

### PR DESCRIPTION
**Pull request by mynamavi**

### CODE REVIEW

**Review by haydenyoung — CHANGES_REQUESTED** [review]
The README.md is missing a lot of text, for example lines 2 - 4 in upstream is missing from the pull request.

Has the latest pull request been force committed because git shouldn't allow the commit if the readme is in conflict locally.

**Review by haydenyoung — CHANGES_REQUESTED** [review]
You'll need to do a full diff of the readme.md files. There is still a lot of text missing.

**Review by haydenyoung — CHANGES_REQUESTED** [review]
There's still code in upstream being overwritten by this pull request.

**Review by haydenyoung — CHANGES_REQUESTED** [review]
class-collectionpress-settings:

missing a lot of changes:

L112 - Incorrect text. Text should be updated to match upstream

L141 - $desc has been reintroduced. This shouldn't be there.

L158 - Indenting is broken.

**Review by haydenyoung — CHANGES_REQUESTED** [review]
lang/bkcpress-nb? Not sure what this is? Is this a backup file? If so, remove; we don't need backup files in source control, defeats the purpose of having source control. Just delete.

**Review by haydenyoung — CHANGES_REQUESTED** [review]
lang/cpress-nb_NO.po This file seems to be completely in conflict. It is still showing strings that are obsolete (L70 -71) and strings are empty/in the wrong place in the pull request. If nothing has been added, just use the upstream version of the po file.

**Comment by mynamavi** [comment]
Please check it

**Pull request closed without merging**
